name: NPM Publish CI

on:
  workflow_dispatch:
  release:
    types: [ created ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm install
      - run: npm run build
      - run: npm publish --access public --otp=3382876452939035
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_GITHUB_RELEASE_CLI_0 }}
